name: Train ML Model with MLflow
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: mlflow-env
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge mlflow scikit-learn pandas numpy matplotlib seaborn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify MLflow installation
      shell: bash -l {0}
      run: |
        mlflow --version
        python -c "import mlflow; print(f'MLflow version: {mlflow.__version__}')"
    
    - name: Copy data to MLProject directory
      run: |
        echo "Copying penguins_preprocessed.csv to MLProject directory..."
        cp penguins_preprocessed.csv MLProject/
        echo "Files in MLProject after copy:"
        ls -la MLProject/
    
    - name: Run MLflow project
      shell: bash -l {0}
      run: |
        echo "Running MLflow project from MLProject directory..."
        cd MLProject
        mlflow run .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          MLProject/mlruns/
          MLProject/*.jpg
          MLProject/*.png
          MLProject/*.pkl
        retention-days: 7
      continue-on-error: true
