name: Train ML Model

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy matplotlib seaborn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run MLflow project
      run: |
        cd MLProject
        mlflow run . --no-conda
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: |
          MLProject/mlruns
          MLProject/screenshot_*.jpg
